### ISSUE TITLE
Flashpoll Issues

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-opin#749]
**OPIN Integration Bugs**
- [ ] CK Editor broken in Flashpoll projects
- [ ] Cant delete flashpoll project (delete button only visible if project is in draft)
- [ ] No poll results shown after poll finishes (https://github.com/liqd/euth_wagtail/issues/729)
- [ ] When deleting a question in Flashhpoll an error 500 appears after "saving the changes". (When deleting a question in a poll that was already published and filled out by some participants, an error 500 appears when trying to save the changes, everytime you click on the flashpoll project.)
- [ ] Results of poll are not visible (I created a poll with two questions, first one open, second one multiple choice, but the results are visible in the result tab. Actually I am also not sure, if that is the place, where they should be displayed) https://github.com/liqd/euth_wagtail/issues/724
- [ ] The date you can select in Flashpoll project is one hour later than the time that appears in the "Poll: Description" tab. (https://github.com/liqd/euth_wagtail/issues/722)
- [ ] "Flashpoll phase" and "Poll: Description" contain almost the same features (titel, description, date selection) (https://github.com/liqd/euth_wagtail/issues/721)
- [ ] No visualization of the "open" question's answer after poll (https://github.com/liqd/euth_wagtail/issues/728)
- [ ] In the ranking questions, it is not clear that you are able to rank the items or how to do so. (https://github.com/liqd/euth_wagtail/issues/723)

**OPIN Integration Issues**
- [ ] use proper forms in dashboard
- [ ] use open street map for the map
- [ ] merge phase date picker fields with the date picker fields for flashpoll
- [ ] factor our Flaspoll client into its own class
- [ ] split flashpoll functions into smaller units (a lot easier after factoring out the client and using proper forms)

**Flashpoll App**
- [ ] In the Opin APP when answering a "open" question the writing overlaps. (https://github.com/liqd/euth_wagtail/issues/727)
- [ ] In the ranking questions, it is not clear that you are able to rank the items or how to do so. (https://github.com/liqd/euth_wagtail/issues/723)

**Comment by MagdaN** [comment]
no visualization for open questions, download needed
